### PR TITLE
Removed docs/ from git management

### PR DESCRIPTION
**Pull request by shukawam**
I noticed that the currently [Japanese documentation](https://principlesofchaos.org/ja/) is not up to date. I think this is due to the fact that building Hugo content locally and pushing the results to GitHub. In this way, contributors only need to manage content/* and config.toml to build Hugo content using GitHub Actions, which is convenient for both(contributor and manager).

Since the content after the build via GitHub Actions will be placed in the branch named gh-pages, you need to modify the GitHub Pages settings as follows:

- Branch: gh-pages
- /(root)

image

The translation of the Japanese document was based on a previous PR: [https://github.com/chaos-eng/chaos-eng.github.io/pull/48](https://github.com/chaos-eng/chaos-eng.github.io/pull/48)

Temporarily, the content is available in my repository, and please use it to confirm that everything is fine. (I will remove the public setting after the review.)

github repo: [https://github.com/shukawam/chaos-eng.github.io](https://github.com/shukawam/chaos-eng.github.io)
github pages: [https://shukawam.github.io/chaos-eng.github.io/](https://shukawam.github.io/chaos-eng.github.io/)

### CODE REVIEW

**Comment by lorin** [comment]
The build is failing so I'm going to revert this for now: https://github.com/chaos-eng/chaos-eng.github.io/runs/6149352829

**Comment by lorin** [comment]
Never mind, seems to be working now! Thanks!

**Comment by lorin** [comment]
@shukawam Do you know if we still need the [pages-build-deployment](https://github.com/chaos-eng/chaos-eng.github.io/actions/workflows/pages/pages-build-deployment) workflow?

**Comment by shukawam** [comment]
@lorin The pages-build-deployment workflow is a dynamically executed workflow and cannot be deleted.
Also, the page's status is currently 404. Probably because the configuration of GitHub Pages for chaos-eng.github.io is not yet complete...

ref. https://user-images.githubusercontent.com/62193282/148322321-4a6a2db3-0571-40ad-9f50-bbcca66b5618.png

**Comment by lorin** [comment]
I think this is resolved now.

**Pull request merged**
