### PR TITLE
Mahyarmot patch 1

### PR DESCRIPTION
**Pull request by mahyarmot**
Persian translation

### CODE REVIEW

**Comment by mapmeld** [comment]
Hi @mahyarmot - I worked on the Arabic translation so would want to say a few suggestions. Your translation is very helpful, but right now it is replacing ENcontent; ideally it should be:

- add a new section named FAcontent - Persian translation goes inside
- add a link to the languages list
- add ```FAcontent``` to the CSS used by ARcontent, so it can also be right-to-left

**Comment by mahyarmot** [comment]
Hi Nick,

Thanks for your suggestions. I’ll do it as you proposed. 

Regards,
Mahyar M

**Comment by lorin** [comment]
@mahyarmot Let me know once you've incorporated @mapmeld's suggestions and then I'll review and merge.

**Comment by lorin** [comment]
We've recently changed the structure of this repo so that we generate the site from markdown files (see the README), which should be much easier than the previous approach. 

I'm going to close this PR for now. If you'd still like to contribute a Persian translation, please go ahead and open a new PR.

**Pull request closed without merging**
